### PR TITLE
edit functions to work with OpenMx

### PR DESCRIPTION
**Pull request by maugavilla**
edit check.obj and llcont.MxModel, so that they work with OpenMx objects

### CODE REVIEW

**Comment by ecmerkle** [comment]
Thanks, I will look at it soon!

In the meantime, would you consider adding a test to tests/testthat/test_llcont.R? We have added a bunch of tests there to check that the sum of llcont() equals the model logLik(). Or if you can add an example OpenMx model or two in that file, I could deal with the tests themselves.

**Comment by maugavilla** [comment]
Sure, will add the tests soon

**Comment by ecmerkle** [comment]
The test gave me the error below. If it is easy for you to see the problem, let me know, otherwise I will look at it some more soon.

```
  ── Error ('test_llcont.R:351:5'): OpenMx object ────────────────────────────────
  Error in `mx_lca(data = df, classes = 1L, run = F)`: 
  Function mx_lca() only accepts data of an ordinal (binary or ordered categorical) level of measurement.
```

**Comment by maugavilla** [comment]
DId you dinf out what was the problem? I cant reproduce the error, it seems the test is ignoring this line that changes the data set to ordinal

df[1:4] <- lapply(df, ordered)

**Comment by ecmerkle** [comment]
For some reason it didn't like you renaming `data_mix_ordinal` to `df`. It seems like the `lapply()` line was not needed (the columns of `data_mix_ordinal` were already ordered), so I just used the original data for the model estimation.

**Pull request merged**
